[tool.commitizen]
name = "cz_conventional_commits"
version = "0.16.0"
tag_format = "$major.$minor.$patch$prerelease"
version_files = [
    "naas_drivers/__init__.py",
    "Dockerfile",
    "setup.py:version"
    ]